version: "3.1"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
  api-server:
    image: api-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
